import "./globals.css";
import LayoutProvider from "./layoutprovider";
import SessionWrapper from "./sessionwrapper";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
    <html lang="en">
      <body>
        <LayoutProvider>
        {children}
        </LayoutProvider>
        </body>
    </html>
    </SessionWrapper>
  );
}
